### ISSUE TITLE
树形数据默认全部展开属性未生效

### ISSUE THREAD

**Issue by jserlin** [Spdino/vbt-table#1]
#### 树形数据默认全部展开属性没用
element ui文档属性如下，开始以为是版本问题，试着将你的拉下来，修改ui的版本为2.10最新版本，该属性还是未生效。期望能默认展开
![image](https://user-images.githubusercontent.com/21241627/60700634-3b5ef600-9f2b-11e9-8e63-c74d41a25738.png)

**Comment by Spdino** [comment]
这段时间比较忙，有时间更新下

**Comment by yihaosun** [comment]
我在你封装的组件table里使用总计这个功能，结果总计不能滑动,请问是为什么？

**Comment by Spdino** [comment]
已修复更新

**Comment by yaohui-li** [comment]
树形数据默认全部展开属性没用 这个问题如何处理的
