### ISSUE TITLE
想问问，我是全部都是cdn引入的项目，想问问怎么使用

### ISSUE THREAD

**Issue by RubbbbbY** [Spdino/vbt-table#2]
如果cdn引入需要引用那些文件才能进行使用
![image](https://user-images.githubusercontent.com/19768528/60865347-70838500-a258-11e9-8004-52f2bb183182.png)

**Comment by Spdino** [comment]
在项目中运行yarn lib || npm run lib 打包生成的文件，选择你需要的JS文件
