### ISSUE TITLE
树表格的收缩有些问题

### ISSUE THREAD

**Issue by hsmklook** [Spdino/vbt-table#4]
假如我有3级以上的树表格，我看了一下代码发现只是减去了当前节点的子节点数量，但是如果我子节点下面又展开了子节点，那么你所减去的子节点的数量就不对了。

**Comment by Spdino** [comment]
恩，多级我之前试过，好像是支持的，能否有个事例给我下，谢谢了

**Comment by hsmklook** [comment]
`let jsonArr = [{"id":1,"children":[{"id":10000001,"children":[{"id":11000002,"children":[],"role":"role_21","language":"en_US","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址1"},{"id":11000003,"children":[],"role":"role_31","language":"zh_CN","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址2"}],"role":"role_1","language":"zh_CN","name":"78787","sex":"女","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址0"},{"id":10000002,"children":[{"id":12000002,"children":[],"role":"role_22","language":"en_US","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址1"},{"id":12000003,"children":[],"role":"role_32","language":"zh_CN","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址2"}],"role":"role_2","language":"en_US","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址1"},{"id":10000003,"children":[{"id":13000002,"children":[],"role":"role_23","language":"en_US","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址1"},{"id":13000003,"children":[],"role":"role_33","language":"zh_CN","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址2"}],"role":"role_3","language":"zh_CN","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址2"},{"id":10000004,"children":[],"role":"role_4","language":"en_US","name":"","sex":"女","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址3"},{"id":10000005,"children":[],"role":"role_5","language":"zh_CN","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址4"},{"id":10000006,"children":[],"role":"role_6","language":"en_US","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址5"},{"id":10000007,"children":[],"role":"role_7","language":"zh_CN","name":"","sex":"女","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址6"},{"id":10000008,"children":[],"role":"role_8","language":"en_US","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址7"},{"id":10000009,"children":[],"role":"role_9","language":"zh_CN","name":"","sex":"男","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址8"}],"role":"role_1","language":"zh_CN","name":"name_1","sex":"女","age":18,"rate":5,"address":"地址 地址地址 地址地址 址地址址地址 址地址 址地址  址地址 址地址  址地址 址地址址地址址地址 地址0"}]`

**Comment by hsmklook** [comment]
用这个试一下，你会发现的
补：我忘了说了，情况是这样的，1级节点展开下的多个2级子节点也展开的时候，去收缩1级子节点会出现我说的问题

**Comment by Spdino** [comment]
已经修复更新了。。。

**Comment by hsmklook** [comment]
额，我觉得你那里得递归吧，不然都不能把所有子节点都算进去，我有4、5、6、7.。。。8层的话，你那个循环就没算完了

**Comment by Spdino** [comment]
已更新修复
